<div class="ui field" v-bind:class="{required: $attrs.required}">
    
    <div class="ui right very wide sidebar" v-bind:id="'sidebar_' + $attrs.id" style="width: 640px; background-color: #ffffff; overflow: hidden;">
      
      <div class="ui fluid container" style="border-bottom: 1px solid rgb(221, 221, 221); background-color: white;">
        <div class="ui secondary menu">
          
          <div class="left menu" style="padding-left: 10px;">
            <div class="item" style="padding-left: 0px; margin-left: 0px;">
              <div class="ui basic button" v-on:click="doCloseImageSelectorSlide()">
                <i class="arrow left icon"></i> cancelar
              </div>
            </div>
          </div>

          <div class="right menu" style="padding-left: 10px;">
            <div class="item" style="padding-left: 0px; margin-left: 0px;">
              <div class="ui green disabled button" v-on:click="doAcceptSelectedImage()" v-bind:id="'aceptar_button_' + $attrs.id">
                <i class="check icon"></i> aceptar
              </div>
            </div>
          </div>

        </div>
      </div>

      <div class="ui fluid container" style="padding: 14px; border-bottom: 1px solid rgb(221, 221, 221); background-color: white;">
        <div v-if="imageSelectedName != ''" class="ui segments">
          <div class="ui segment">
            Imagen Seleccionada
          </div>
          <div class="ui segment">
            <img v-bind:src="basepath + 'avatar/sq100/' + imageSelectedName + '.jpg'" style="border-radius: 8px 8px 8px 8px;-moz-border-radius: 8px 8px 8px 8px; -webkit-border-radius: 8px 8px 8px 8px; border: 0px solid #000000; width:100px;" />
          </div>
        </div>
      </div>

      <div class="ui fluid container" style="padding: 14px; background-color: white;">
        
        <div class="ui top attached tabular menu">
          <div class="active item imageSelectorTab" data-tab="upload">Subir Imagen</div>
          <!-- <div class="item imageSelectorTab" data-tab="gallery">Seleccionar de la Galería</div> -->
          <div class="item imageSelectorTab" data-tab="camera">Usar Camara </div>
        </div>

        <div class="ui bottom attached active tab segment" data-tab="upload">
          <table class="ui celled striped selectable table">
            <tbody>

              <tr>
                <td style="min-width:150px; max-width:150px; vertical-align: top;">
                  <div class="ui large label" style="background-color: transparent;">
                    <i class="edit outline icon'"></i>Nombre de la Imagen
                  </div>
                </td> 
                <td>
                  <div class="ui input" style="width:350px;">
                    <input type="text" v-bind:id="'file_upload_name_' + $attrs.id" v-bind:value="uploadImageName">
                  </div>
                </td>
              </tr>

              <tr>
                <td style="min-width:150px; max-width:150px; vertical-align: top;">
                  <div class="ui large label" style="background-color: transparent;">
                    <i class="edit outline icon'"></i>Descripción de la Imagen
                  </div>
                </td> 
                <td>
                  <textarea id="upload_image_description" name="upload_image_description" rows="3" cols="50">${uploadImageDescription}</textarea>
                </td>
              </tr>

              <tr>
                <td style="min-width:150px; max-width:150px; vertical-align: top;">
                  <div class="ui large label" style="background-color: transparent;">
                    <i class="edit outline icon'"></i>Propiedades de la Imagen
                  </div>
                </td> 
                <td>
                  
                  <table>
                    <tr>
                      <td>
                        Type
                      </td>
                      <td>
                        <div class="ui input">
                          <input type="text" readonly="" v-bind:id="'file_upload_typemime_' + $attrs.id" v-bind:value="uploadImageTypemime">
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        Extension
                      </td>
                      <td>
                        <div class="ui input">
                          <input type="text" readonly="" v-bind:id="'file_upload_extension_' + $attrs.id" v-bind:value="uploadImageExtension">
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        Size [bytes]
                      </td>
                      <td>
                        <div class="ui input">
                          <input type="text" readonly="" v-bind:id="'file_upload_size_' + $attrs.id" v-bind:value="uploadImageSize">
                        </div>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

              <tr>
                <td style="min-width:150px; max-width:150px; vertical-align: top;">
                  <div class="ui large label" style="background-color: transparent;">
                    <i class="edit outline icon'"></i>Subir Archivo
                  </div>
                </td> 
                <td>
                  <input type="file" accept="image/*" v-bind:id="'file_' + $attrs.id" style="display: none;"  v-on:change="event => onSelectedFile(event)">
                  <div class="ui blue fluid button" v-on:click="doBrowseFile()">Seleccionar Archivo</div>
                  <br />
                  <div class="ui green fluid disabled button" v-bind:id="'upload_button_' + $attrs.id" v-on:click="event => doUploadImage(event)">Subir Archivo</div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <!--
        <div class="ui bottom attached tab segment" data-tab="gallery" v-bind:id="'gallery_' + $attrs.id">
          <div v-for="(image, index) in galleryData" :key="index" class="ui icon massive basic button galleryButton" v-bind:id="'gallery_button_' + image._id" v-bind:style="'min-width: 100px; min-height: 100px;padding-top: 38px; margin: 10px; background-image: url(\''+ basepath +'avatar\/sq100\/' + image._id + '.jpg\');'" v-on:click="doGallerySelectImage(image._id)">
            <i class="check icon"></i>
          </div>
        </div> -->

        <div class="ui bottom attached tab segment" data-tab="camera">
          TEST
        </div>

      </div>
    </div>

    <div v-for="(image, index) in images" class="ui icon massive button" v-on:click="doOpenImageSelectorSlide(index)" v-bind:style="'min-width: 100px;min-height: 100px;padding-top: 38px;background-image: url(\''+ basepath +'avatar\/sq100\/' + image + '.jpg\');'">
      <i class="pen blue icon" style="color:white;"></i>
    </div>

    <div v-if="(!isMultiple() && !hasImages()) || (isMultiple())" class="ui icon massive basic button" v-on:click="doOpenImageSelectorSlide('_' + (imagesMaxIndex() + 1))" style="min-width: 100px;min-height: 100px;padding-top: 38px;">
      <i class="plus icon"></i>
    </div>

    <select v-if="isMultiple()" v-bind:id="'field_' + $attrs.id" v-bind:name="$attrs.id + '[]'" multiple="" v-bind:form="$attrs.forForm">
          <option v-for="(image, index) in images" :key="index" v-bind:value="image" selected="selected">${image}</option>
    </select>

    <select v-if="!isMultiple()" v-bind:id="'field_' + $attrs.id" v-bind:name="$attrs.id" v-bind:form="$attrs.forForm">
          <option v-for="(image, index) in images" :key="index" v-bind:value="image" selected="selected">${image}</option>
    </select>
    
    <p v-if="$attrs.info != ''" style="font-size:.8em">${ $attrs.info }</p>
</div>