<div>

<div class="ui field" v-bind:class="{required: $attrs.required}">
    <div class="ui input" style="width: 450px;" v-bind:class="{disabled: $attrs.readOnly}">
      <input type="password" placeholder="" v-bind:id="'field_' + $attrs.id" v-bind:name="$attrs.id" v-bind:form="$attrs.forForm">
    </div>
</div>
<div class="ui field" v-bind:class="{required: $attrs.required}" style="margin-top:10px;">
  <div class="ui input" style="width: 450px;" v-bind:class="{disabled: $attrs.readOnly}">
    <input type="password" placeholder="" v-bind:id="'field_repeat_' + $attrs.id">
  </div>
</div>

<p v-if="$attrs.info != ''" style="font-size:.8em">${ $attrs.info }</p>
</div>