<div class="ui field" v-bind:class="{required: $attrs.required}">
    <div class="ui input" style="width: 450px;" v-bind:class="{disabled: $attrs.readOnly}">
      <input v-if="!isTextArea()" type="text" placeholder="" v-bind:id="'field_' + $attrs.id" v-bind:name="$attrs.id" v-bind:form="$attrs.forForm">
      <textarea v-if="isTextArea()" cols="60" v-bind:id="'field_' + $attrs.id" v-bind:name="$attrs.id" v-bind:form="$attrs.forForm" v-bind:rows="$attrs.options.rows" ></textarea>
    </div>
    <p v-if="$attrs.info != ''" style="font-size:.8em">${ $attrs.info }</p>
</div>