<div class="ui fluid container main-container">
    <div id="___id_" class="ui padded grid">
        <div class="column">
            <table class="ui celled striped table">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th>ID</th>
                        <th>&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            FIELD
                        </td>
                        <td>
                            FIELD
                        </td>
                        <td>
                            FIELD
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="3">
                            FOOTER
                        </th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>