<div class="ui fluid container main-container">
    <div id="___id_" class="ui padded grid">
        <div class="column">
            <table class="ui celled striped table">
                <thead>
                    <tr>
                        <!-- rownum -->
                        <th style="width:36px;">#</th>
                        <!-- fields -->
                        <th v-for="(field, fieldIndex) in tableFields" :key="fieldIndex">
                            ${field.label}
                        </th>
                        <!-- links -->
                        <th v-if="_.size(linksFields) > 0">&nbsp;</th>
                        <!-- actions -->
                        <th v-if="_.size(actionsFields) > 0">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(dataRow, rowIndex) in data.objects" :key="rowIndex">
                        <td>&nbsp;</td>
                        <td v-for="(rowField, fieldIndex) in tableFields" :key="fieldIndex">
                            <template v-if="rowField.renderType == 'LINK'">
                                <a href="#">${dataRow[fieldIndex]}</a>
                            </template>
                            <template v-else>
                                ${dataRow[fieldIndex]}
                            </template>
                        </td>
                        <td v-if="_.size(linksFields) > 0">
                            <template v-for="(rowLink, linkIndex) in linksFields">
                                <a v-bind:class="'ui ' + rowLink.style + ' button'" v-bind:href="rowLink.urlMap">${rowLink.label}</a>
                            </template>
                        </td>
                        <td v-if="_.size(actionsFields) > 0" class="right aligned" style="padding-right: 4px;">
                            <div class="ui basic buttons">
                            <template v-for="(rowAction, linkIndex) in actionsFields">
                                <a class="ui icon button" v-bind:href="rowAction.urlMap"><i v-bind:class=" rowAction.style + ' icon'"></i></a>
                            </template>
                            </div>
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th v-bind:colspan="colsNum">
                            <div class="ui right floated pagination mini menu">
        
                                <a class="icon item"><i class="left chevron icon"></i></a>

                                <a class="active item">1</a>
                                <a class="item">2</a>
                                <a class="item">3</a>
                                
                                <div class="icon item"><i class="ellipsis horizontal icon"></i></div>
                                        
                                <a class="icon item" ><i class="right chevron icon"></i></a>
                                
                            </div>
                        </th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>