<div class="ui fluid container main-container">
    <form ref="selectorForm" id="___id__form" name="___id__form" method="post" enctype="multipart/form-data">
        <input type="hidden" id="datasource" name="datasource" v-bind:value="datasource" />
        <input type="hidden" id="token" name="token" v-bind:value="token" />
        <div id="___id_" class="ui padded grid">
            <div class="thirteen wide column">
                
                <div class="ui top attached tabular menu" style="padding-left: 14px; padding-right: 14px;">
                    <template v-for="(groupFields, groupId, index) in fields.main">
                        <a class="item formtab" v-bind:class="(index == 0) ? 'active' : ''" v-bind:data-tab="groupId">${getGroupName(groupId)}</a>
                    </template>
                </div>
                <template v-for="(groupFields, groupId, index) in fields.main">
                    <div class="ui bottom attached tab segment" v-bind:class="(index == 0) ? 'active' : ''" v-bind:data-tab="groupId" style="padding: 0px; border-width: 0px; margin-top: -1px;">
                        
                        <table class="ui celled striped selectable table">
                            
                            <tbody>

                                <tr v-for="(field, fieldIndex) in groupFields" :key="fieldIndex">
                                    <td style="width: 280px;vertical-align: top;">
                                        
                                        <div class="ui large label" style="background-color: transparent;">
                                            <i v-bind:class="field.icon + ' icon'"></i> ${field.label}
                                        </div>
                                        
                                        <div v-if="field.help != ''" class="ui icon basic mini help button right floated helpPopup" v-bind:data-html="field.help" data-position="right center" data-variation="very wide">
                                            <i class="help blue icon"></i>
                                        </div>
                                    </td>
                                    <td>
                                    <template v-if="field.component == 'image-selector'">
                                        <ElementImageSelector v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementImageSelector>
                                    </template>
                                    <template v-if="field.component == undefined">
                                    <ElementTextBox v-if="field.type == 'text'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementTextBox>
                                    <ElementNumberBox v-if="field.type == 'integer'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementNumberBox>
                                    <ElementSwitcherBox v-if="field.type == 'boolean01'" valueAs="binary" v-bind:editAs="field.editAs" v-bind:id="field.id" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementSwitcherBox>
                                    <ElementSwitcherBox v-if="field.type == 'boolean'" valueAs="boolean" v-bind:editAs="field.editAs" v-bind:id="field.id" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementSwitcherBox>
                                    <ElementOptionsSelector v-if="field.type == 'options'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementOptionsSelector>
                                    <ElementOptionsSelector v-if="field.type == 'objectsr'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementOptionsSelector>
                                    <ElementOptionsSelector v-if="field.type == 'objectr'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementOptionsSelector>
                                    <ElementJsonEditor v-if="field.type == 'json'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementJsonEditor>
                                    <ElementTagsBox v-if="field.type == 'tags'" v-bind:editAs="field.editAs" v-bind:id="field.id" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementTagsBox>
                                    <ElementDateBox v-if="field.type == 'datetime'" v-bind:editAs="field.editAs" v-bind:id="field.id" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementDateBox>
                                    </template>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                        
                    </div>

                </template>
            </div>

            <div class="three wide column" style="padding-left: 0px;padding-top: 53px;">
                
                <template v-for="(groupFields, groupId, index) in fields.side">
                    <table v-for="(field, fieldIndex) in groupFields" :key="fieldIndex" class="ui celled striped loaded selectable table">
                        <thead>
                            <tr>
                                <th >
                                    <div class="ui large label" style="background-color: transparent;">
                                        <i v-bind:class="field.icon + ' icon'"></i> ${field.label}
                                    </div>
                                            
                                    <div v-if="field.help != ''" class="ui icon basic mini help button right floated helpPopup" v-bind:data-html="field.help" data-position="left center" data-variation="very wide">
                                        <i class="help blue icon"></i>
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <ElementTextBox v-if="field.type == 'text'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementTextBox>
                                    <ElementNumberBox v-if="field.type == 'integer'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementNumberBox>
                                    <ElementSwitcherBox v-if="field.type == 'boolean01'" valueAs="binary" v-bind:editAs="field.editAs" v-bind:id="field.id" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementSwitcherBox>
                                    <ElementSwitcherBox v-if="field.type == 'boolean'" valueAs="boolean" v-bind:editAs="field.editAs" v-bind:id="field.id" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementSwitcherBox>
                                    <ElementOptionsSelector v-if="field.type == 'options'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementOptionsSelector>
                                    <ElementOptionsSelector v-if="field.type == 'objectsr'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementOptionsSelector>
                                    <ElementOptionsSelector v-if="field.type == 'objectr'" v-bind:id="field.id" v-bind:editAs="field.editAs" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementOptionsSelector>
                                    <ElementTagsBox v-if="field.type == 'tags'" v-bind:editAs="field.editAs" v-bind:id="field.id" v-bind:label="field.label" v-bind:data="objectData" v-bind:default="field.default" v-bind:help="field.help" v-bind:info="field.info" v-bind:required="field.required" v-bind:readOnly="field.readOnly" v-bind:validation="getFieldValidationOptions(field.options)" v-bind:file="getFieldFileOptions(field.options)" v-bind:options="getFieldOptions(field.options)"></ElementTagsBox>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </template>
            </div>
        </div>
    </form>
</div>