<div class="ui container" style="margin-top: 40px;">
    <div class="ui grid">
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui medium header" style="font-family: 'Dosis', sans-serif; font-size: 26px; font-weight: 700; letter-spacing: 2px; text-align: left; color: #BF125D; text-shadow: 2px 0px 10px #ffffff;">Destinos</div>
            </div>
        </div>
        <div class="row">
            <div class="sixteen wide column">
                <div class="ui four doubling cards">
                    <a v-for="(cardData, cardIndex) in data" :key="cardIndex" class="ui raised card" v-bind:href="parseStringBlocks(urlLinkMap, cardData)">
                        <div class="image">
                            <img v-bind:src="parseStringBlocks(imgSrcMap, cardData)" />
                        </div>
                        <div class="content" style="font-family: 'Dosis', sans-serif;">
                            <div class="header" style="margin-top: 5px; font-size: 26; color: #4A4A4A;">${cardData.label}</div>
                            <div class="meta right aligned" style="margin-top: 5px;">
                                <span v-if="cardData.preciodesde" style="color: #4A4A4A;">Desde</span>
                                <span style="color: #E81F76; font-weight: bold;">${cardData.moneda} ${cardData.precio}</span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>