
<div class="ui fluid container" style="margin-top: 40px; background-color: #f5f5f5;">
    <div class="ui container" style="padding-bottom: 28px;">
        <div class="ui grid">
            <div class="row">
                <div class="eleven wide column">

                    <div class="ui segment">
                        <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 2px; text-align: left; margin-top: 2px;color:#4A4A4A;">Contacto</div>
                        <form class="ui form" name="contacto_form" id="contacto_form" action="" method="post" enctype="multipart/form-data">
                            <div class="ui fields">
                                <div class="eight wide field">
                                    <label style="font-family: 'Dosis', sans-serif; letter-spacing: 2px;">Nombres y Apellido</label>
                                    <input type="text" name="contacto_nombre" id="contacto_nombre" />
                                </div>
                                <div class="eight wide field">
                                    <label style="font-family: 'Dosis', sans-serif; letter-spacing: 2px;">email</label>
                                    <input type="text" name="contacto_email" id="contacto_email" />
                                </div>
                            </div>
                            <div class="ui fields">
                                <div class="eight wide field">
                                    <label style="font-family: 'Dosis', sans-serif; letter-spacing: 2px;">Telefono</label>
                                    <input type="text" name="contacto_telefono" id="contacto_telefono" />
                                </div>
                            </div>
                            <div class="ui fields">
                                <div class="five wide field">
                                    <div class="g-recaptcha" data-sitekey="6Ld5jKwZAAAAANsVCnzG-3VFJYCYKMTfKp9eexb7"></div>
                                </div>
                            </div>
                            <div class="ui fields">
                                <div class="sixteen wide field">
                                    <label style="font-family: 'Dosis', sans-serif; letter-spacing: 2px;">Mensaje</label>
                                    <textarea name="contacto_message" id="contacto_message" rows="3" ></textarea>
                                </div>
                            </div>
                            <div class="ui fields">
                                <div class="sixteen wide field">
                                <div class="ui basic button" style="border: 0px solid rgba(255, 255, 255, 0) !important; background-color: #F7BE00; font-weight: bold; color: #ffffff; font-family: 'Dosis', sans-serif; letter-spacing: 2px;" v-on:click="doSendData()">Enviar Datos</div> 
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
                
            </div>
        </div>
    </div>
</div>