<div class="ui fluid container" style="background-color: #e81f76; padding-top: 50px;">
    <div class="ui container">
        <div class="ui grid">
            <div class="row">
                <div class="five wide column">
                    <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 1px; text-align: left; margin-top: 2px; color: #ffffff; font-size: 14px;">CONTACTANOS</div>
                    <form class="ui form" action="#">
                        <div class="ui field">
                            <label style="font-family: 'Dosis', sans-serif; font-size: 12px; letter-spacing: 1px; color: #ffffff; font-weight: 400;">Nombre</label>
                            <input type="text"/>
                        </div>
                        <div class="ui field">
                            <label style="font-family: 'Dosis', sans-serif; font-size: 12px; letter-spacing: 1px; color: #ffffff; font-weight: 400;">Apellido</label>
                            <input type="text"/>
                        </div>
                        <div class="ui field">
                            <label style="font-family: 'Dosis', sans-serif; font-size: 12px; letter-spacing: 1px; color: #ffffff; font-weight: 400;">Email</label>
                            <input type="text"/>
                        </div>
                        <div class="ui field">
                            <label style="font-family: 'Dosis', sans-serif; font-size: 12px; letter-spacing: 1px; color: #ffffff; font-weight: 400;">Mensaje</label>
                            <textarea rows="3"></textarea>
                        </div>
                        <div style="text-align: right;">
                            <button class="ui button" style="border: 0px solid rgba(255, 255, 255, 0) !important; background-color: #F7BE00; font-weight: bold; color: #ffffff; font-family: 'Dosis', sans-serif; letter-spacing: 2px;">Enviar</button>
                        </div>
                    </form>
                </div>
                <div class="three wide column">
                    <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 1px; text-align: left; margin-top: 2px; color: #ffffff; font-size: 14px;">EMPRESA</div>
                    <a href="#" style="font-family: 'Dosis', sans-serif; font-size: 12px; letter-spacing: 1px; color: #ffffff; font-weight: 400;">Acerca de</a>
                </div>
                <div class="three wide column">
                    <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 1px; text-align: left; margin-top: 2px; color: #ffffff; font-size: 14px;">ATENCION AL CLIENTE</div>
                    <div style="font-family: 'Dosis', sans-serif; font-size: 12px; letter-spacing: 1px; color: #ffffff; font-weight: 400;">Horario de Atención <br />8:00hs - 18:00hs<br />+595 20 000 000<br />+595 981 000 000</div>
                </div>
                <div class="five wide column">
                    <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 1px; text-align: left; margin-top: 2px; color: #ffffff; font-size: 14px;">SIGUENOS</div>
                    <div style="font-family: 'Dosis', sans-serif; font-size: 12px; letter-spacing: 1px; color: #ffffff; font-weight: 400;">
                        <a href="#" style="padding: 5px;">
                            <i class="instagram icon" style="color:#ffffff !important; font-size: 25px;"></i>
                        </a>
                        <a href="#" style="padding: 5px;">
                            <i class="facebook icon" style="color:#ffffff !important; font-size: 25px;"></i>
                        </a>
                        <a href="#" style="padding: 5px;">
                            <i class="twitter icon" style="color:#ffffff !important; font-size: 25px;"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>