
<div class="ui container" style="margin-top: 40px; padding-bottom: 28px;">
    <div class="ui grid">
        <div class="row">
            <div class="eleven wide column">
                <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 2px; text-align: left; margin-top: 2px;color:#4A4A4A;">PROPOSITO</div>
                <div style="font-family: 'Dosis', sans-serif; letter-spacing: 0px; text-align: justify; margin-bottom: 40px; margin-top: 2px; color: #4A4A4A; font-size: 18px;">
                    <p>
                    Somos una Agencia de Viajes que forma parte del grupo de empresas de la Financiera Paraguayo Japonesa, que cuenta con años de experiencia en el mercado local. El propósito de la Financiera conjuntamente con la Agencia de Viajes es ofrecer a sus clientes y/o funcionarios un servicio de asesoramiento de viajes personalizado acompañado de la mejor tecnología en diseños de webside dentro del turismo.
                    </p>
                    <p>
                    La agencia de viajes busca hacer más fácil, accesible y agradable la experiencia de organizar un viaje ya sea de ocio o de negocios brindando asesores con experiencias en el rubro y herramientas con toda la información necesaria para que organizar un viaje sea un verdadero placer.
                    </p>
                </div>
                <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 2px; text-align: left; margin-top: 2px;color:#4A4A4A;">MISION</div>
                <div style="font-family: 'Dosis', sans-serif; letter-spacing: 0px; text-align: justify; margin-bottom: 40px; margin-top: 2px; color: #4A4A4A; font-size: 18px;">
                    <p>
                    Complacer a nuestros clientes. Somos una empresa creadora de experiencias de viajes, que garantiza la calidad y el respaldo en cada servicio.
                    </p>
                </div>

                <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 2px; text-align: left; margin-top: 2px;color:#4A4A4A;">VISION</div>
                <div style="font-family: 'Dosis', sans-serif; letter-spacing: 0px; text-align: justify; margin-bottom: 40px; margin-top: 2px; color: #4A4A4A; font-size: 18px;">
                    <p>
                    Buscamos modernizar el mundo del turismo a través de la tecnología de innovación para la venta y acceso de servicios turísticos a primera mano.
                    </p>
                    <p>
                    Consolidarnos a mediano plazo como una Agencia de Viajes confiable, segura y competitiva dentro del mercado del Turismo Paraguayo; motivados por un alto grado de responsabilidad, profesionalismo y experiencia en el rubro.
                    </p>
                </div>
                <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 2px; text-align: left; margin-top: 2px;color:#4A4A4A;">VALORES</div>
                <div style="font-family: 'Dosis', sans-serif; letter-spacing: 0px; text-align: justify; margin-bottom: 40px; margin-top: 2px; color: #4A4A4A; font-size: 18px;">
                    <div class="ui list">
                        <div class="item">
                            <i class="caret right icon" style="color:#4A4A4A;"></i>
                            <div class="content">
                            Respeto
                            </div>
                        </div>
                        <div class="item">
                            <i class="caret right icon" style="color:#4A4A4A;"></i>
                            <div class="content">
                            Empatía
                            </div>
                        </div>
                        <div class="item">
                            <i class="caret right icon" style="color:#4A4A4A;"></i>
                            <div class="content">
                            Responsabilidad
                            </div>
                        </div>
                        <div class="item">
                            <i class="caret right icon" style="color:#4A4A4A;"></i>
                            <div class="content">
                            Amabilidad
                            </div>
                        </div>
                        <div class="item">
                            <i class="caret right icon" style="color:#4A4A4A;"></i>
                            <div class="content">
                            Solvencia
                            </div>
                        </div>
                        <div class="item">
                            <i class="caret right icon" style="color:#4A4A4A;"></i>
                            <div class="content">
                            Honestidad
                            </div>
                        </div>
                        <div class="item">
                            <i class="caret right icon" style="color:#4A4A4A;"></i>
                            <div class="content">
                            Calidad
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>