
<div class="ui fluid container" style="margin-top: 40px; background-color: #f5f5f5;">
    <div class="ui container" style="padding-bottom: 28px;">
        <div class="ui grid">
            <div class="row">
                <div class="sixteen wide column">

                    <div class="ui segment" style="padding-top: 100px;padding-bottom: 100px;">
                        <div style="color: rgb(74, 74, 74);text-align: center;font-size: xx-large;"><i v-bind:class="icon + ' icon'"></i></div>
                        <div class="ui large header" style="font-family: Dosis, sans-serif;letter-spacing: 2px;text-align: left;margin-top: 2px;color: rgb(74, 74, 74);text-align: center; color:#E81F76;" v-html="title"></div>
                        <div class="ui medium header" style="font-family: Dosis, sans-serif;letter-spacing: 2px;text-align: left;margin-top: 2px;color: rgb(74, 74, 74);text-align: center;" v-html="message"></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>