
<div class="ui fluid container" style="margin-top: 40px; background-color: #f5f5f5;">
    <div class="ui container" style="padding-bottom: 28px;">
        <div class="ui grid">
            <div class="row">
                <div class="sixteen wide column">

                    <div class="ui segment" >
                        
                        <div class="ui medium header" style="font-family: Dosis, sans-serif;letter-spacing: 2px;text-align: left;margin-top: 2px;color: rgb(74, 74, 74);text-align: center;">${message}</div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>