
<div class="ui fluid container" style="margin-top: 40px; background-color: #f5f5f5;">
    <div class="ui container" style="padding-bottom: 28px;">
        <div class="ui grid">
            <div class="row">
                <div class="eleven wide column">

                    <div class="ui segment">
                        <div class="ui medium header" style="font-family: 'Dosis', sans-serif; letter-spacing: 2px; text-align: left; margin-top: 2px;color:#4A4A4A;">Datos Personales</div>
                        <form class="ui form" name="reserva_form" id="reserva_form" action="" method="post" enctype="multipart/form-data">
                            <input type="hidden" name="reserva_token" id="reserva_token" v-bind:value="token" />
                            <div class="ui fields">
                                <div class="eight wide field">
                                    <label style="font-family: 'Dosis', sans-serif; letter-spacing: 2px;">Nombres</label>
                                    <input type="text" name="reserva_nombres" id="reserva_nombres" />
                                </div>
                                <div class="eight wide field">
                                <label style="font-family: 'Dosis', sans-serif; letter-spacing: 2px;">Apellidos</label>
                                    <input type="text" name="reserva_apellidos" id="reserva_apellidos" />
                                </div>
                            </div>
                            <div class="ui fields">
                                <div class="eight wide field">
                                    <label style="font-family: 'Dosis', sans-serif; letter-spacing: 2px;">email</label>
                                    <input type="text" name="reserva_email" id="reserva_email" />
                                </div>
                                <div class="eight wide field">
                                    <label style="font-family: 'Dosis', sans-serif; letter-spacing: 2px;">Telefono</label>
                                    <input type="text" name="reserva_telefono" id="reserva_telefono" />
                                </div>
                            </div>
                            <div class="ui fields">
                                <div class="five wide field">
                                    <div class="g-recaptcha" data-sitekey="6Ld5jKwZAAAAANsVCnzG-3VFJYCYKMTfKp9eexb7"></div>
                                </div>
                            </div>
                            <div class="ui fields">
                                <div class="sixteen wide field">
                                    <label style="font-family: 'Dosis', sans-serif; letter-spacing: 2px;">Mensaje</label>
                                    <textarea name="reserva_message" id="reserva_message" rows="3" ></textarea>
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
                <div class="four wide column">
                    <div class="ui segment">
                        <div style="font-family: 'Dosis', sans-serif; letter-spacing: 0px; text-align: left; color: #4A4A4A; margin-bottom: 10px; font-weight: 700; font-size: 12px;">
                        ${data.label}      
                        </div>
                        <div style="font-family: 'Dosis', sans-serif; letter-spacing: 0px; text-align: left; color: #4A4A4A; margin-bottom: 10px;">
                            <span v-if="data.preciodesde" style="color: #4A4A4A;">Desde</span>
                            <span style="color: #E81F76; font-weight: bold;">${data.moneda} ${data.precio}</span> 
                        </div>
                        <div style="font-family: 'Dosis', sans-serif; letter-spacing: 0px; text-align: left; color: #4A4A4A; margin-bottom: 10PX;">
                            <div class="ui basic fluid button" style="border: 0px solid rgba(255, 255, 255, 0) !important; background-color: #F7BE00; font-weight: bold; color: #ffffff; font-family: 'Dosis', sans-serif; letter-spacing: 2px;" v-on:click="doSendData()">Enviar Datos</div>                         
                        </div>
                        <div style="font-family: 'Dosis', sans-serif; letter-spacing: 0px; text-align: left; color:#4A4A4A;">
                            <span>Hasta 16 cuotas!</span>
                            <br/>
                            <span>Financiar con FPJ</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>