<div class="ui fixed secondary large menu" style="min-height: 50px; background-color: #ffffff;">
    <div class="ui container">
        <a v-bind:href="basepath + 'v2'" class="item" style="padding: 1px;"> <img src="http://www.nosvamoos.com/assets/img/logomagenta.png" class="logo-img" style="width: 200px;"> </a>
        <a v-bind:href="basepath + 'v2'" class="item">Home</a>
        <a v-bind:href="basepath + 'v2nosotros'" class="item">Nosotros</a>
        <a v-bind:href="basepath + 'v2contacto'" class="item">Contacto</a>
    </div>
</div>