<div>
    <div class="ui right very wide sidebar" v-bind:id="stateActionData.toState + '_sidebar'" style="width: 750px; background-color: #ffffff; overflow: scroll;">
                                    
        <div class="ui fluid container" style="border-bottom: 1px solid rgb(221, 221, 221); background-color: white;">
            <div class="ui secondary menu">
            
                <div class="left menu" style="padding-left: 10px;">
                    <div class="item" style="padding-left: 0px; margin-left: 0px;">
                    <div class="ui basic button" v-on:click="doCloseStateSlider({'slider':stateActionData.toState})">
                        <i class="arrow left icon"></i> cancelar
                    </div>
                    </div>
                </div>

                <div class="right menu" style="padding-left: 10px;">
                    <div class="item" style="padding-left: 0px; margin-left: 0px;">
                        <button v-bind:class="'ui fluid ' + stateActionData.style + ' button'" v-on:click="doSendStateAction()">
                            ${stateActionData.label}
                        </button>
                    </div>
                </div>

            </div>
            
        </div>

        <div class="ui fluid container" style="padding: 14px; border-bottom: 1px solid rgb(221, 221, 221); background-color: white;">
            
            <form ref="editorForm" v-bind:id="referenceName + '_form'" name="referenceName + '_form'" method="post" enctype="multipart/form-data">
            </form>
            
            <table class="ui celled striped selectable table">
                <tbody>

                    
                    <tr v-for="(field, fieldIndex) in stateActionData.toStateInputData" :key="fieldIndex">
                        <td style="width: 280px;vertical-align: top;">
                            
                            <div class="ui large label" style="background-color: transparent;">
                                <i v-bind:class="field.uiOptions.icon + ' icon'"></i> ${field.uiOptions.label}
                            </div>
                            
                            <div v-if="field.uiOptions.help != ''" class="ui icon basic mini help button right floated helpPopup" v-bind:data-html="field.uiOptions.help" data-position="right center" data-variation="very wide">
                                <i class="help blue icon"></i>
                            </div>
                        </td>
                        <td>

                            <ElementTextField v-if="field.type == 'text'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementTextField>
                            <ElementIntegerField v-if="field.type == 'integer'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementIntegerField>
                            <ElementDateField v-if="field.type == 'datetime'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementDateField>
                            <ElementOptionsField v-if="field.type == 'options'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementOptionsField>
                            <ElementOptionsField v-if="field.type == 'objectr'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementOptionsField>
                            <ElementOptionsField v-if="field.type == 'objectsr'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementOptionsField>
                            <ElementSwitcherField v-if="field.type == 'boolean' || field.type == 'boolean01'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementSwitcherField>
                            <ElementTagsField v-if="field.type == 'tags'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementTagsField>
                            <ElementPasswordField v-if="field.type == 'password'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementPasswordField>
                            <ElementSchemaFormField v-if="field.type == 'subform'" v-bind:id="referenceName + '_form_' + fieldIndex + '_field'" v-bind:forForm="referenceName + '_form'" v-bind:field="field" v-bind:fieldIndex="fieldIndex" v-bind:data="{}" v-bind:urlMaps="urlMaps"></ElementSchemaFormField>

                        </td>
                    </tr>

                </tbody>
            </table>
        </div>

    </div>

    <div v-bind:class="'ui fluid ' + stateActionData.style + ' button'" style="margin-bottom:14px;" v-bind:id="$attrs.id" v-on:click="doStateAction()">
        ${stateActionData.label}
    </div>
</div>

