<div class="ui fluid container main-container">
    <div class="ui secondary menu module-menu">
        <div class="left menu">
            <div class="item">
                <div class="ui breadcrumb">
                    <div class="active section">Board</div>
                </div>    
            </div>
        </div>
        <div class="right menu">
            <div class="item">
                <div class="ui action input">
                    <input type="text" id="search" name="search" placeholder="Search...">
                    <button id="searchbutton" class="ui icon button">
                        <i class="search blue icon"></i>
                    </button>
                </div>
            </div>
            <a id="filter-button" class="ui item blue filters button">
                <i class="filter icon"></i> Filtros
            </a>
            
            <button class="ui item basic button">
                <i class="plus green icon"></i> nuevo
            </button>
        </div>
    </div>
</div>