<div class="ui fluid container main-container" style="position: fixed; z-index: 100; border-bottom: 1px solid #dddddd; background-color: white;">
    <div class="ui secondary menu module-menu">
        <div class="left menu">
            <div class="item">
                <div class="ui breadcrumb">
                    <div v-if="title.type == 'text'" class="active section">${title.text}</div>
                </div>    
            </div>
        </div>
        <div class="right menu">
            <!-- SEARCH -->
            <!-- 
            <div class="item">
                <div class="ui action input">
                    <input type="text" id="search" name="search" placeholder="Search...">
                    <button id="searchbutton" class="ui icon button">
                        <i class="search blue icon"></i>
                    </button>
                </div>
            </div>
            -->
            <!-- FILTERS -->
            <!--
            <a id="filter-button" class="ui item blue filters button">
                <i class="filter icon"></i> Filtros
            </a>
            -->
            <!-- ACTIONS -->
            <div class="item" v-for="(item, index) in actions" style="padding-left: 0px; margin-left: 0px;">
                <a v-if="item.type == 'link'" v-bind:class="'ui ' + item.style + ' button'" v-bind:href="parseStringBlocks(item.urlMap, {})">
                    <i v-bind:class="item.icon"></i> ${item.label}
                </a>
                <button v-if="item.type == 'actions'" v-bind:class="'ui ' + item.style + ' button'" v-on:click="doComponentAction(item.actions, {}, $event)">
                    <i v-bind:class="item.icon"></i> ${item.label}
                </button>
            </div>
        </div>
    </div>
</div>