<div>
    <button class="ui button" v-bind:class="[buttonClass]" v-on:click="doClick">
    Colors
    </button>
    <button class="ui icon button" v-bind:class="[buttonClass]" v-on:click="doData">
    <i class="icon" v-bind:class="[iconClass]"></i> Animals
    </button>
</div> 
<!--
<div class="pushable">
  <div class="ui very wide sidebar inverted vertical menu">
    <a class="item">
      1
    </a>
    <a class="item">
      2
    </a>
    <a class="item">
      3
    </a>
  </div>
  <div class="dimmed pusher">
    Prueba de Contenido de Sitio
  </div>
</div>
-->
