<div class="ui visible left vertical inverted sidebar labeled icon menu" style="min-width:100px;">
    <a class="item" style="padding-right: 8px; padding-left: 8px; min-width:100%;">
        <i class="home olive icon"></i>
        ITEM
    </a>
    <a class="item" style="padding-right: 8px; padding-left: 8px; min-width:100%;">
        <i class="user grey icon"></i>
        ITEM
    </a>
    <a class="item" style="padding-right: 8px; padding-left: 8px; min-width:100%;">
        <i class="piggy bank grey icon"></i>
        ITEM
    </a>
    <a class="item" style="padding-right: 8px; padding-left: 8px; min-width:100%;">
        <i class="chart line grey icon"></i>
        Item
    </a>
    <a class="item" style="padding-right: 8px; padding-left: 8px; min-width:100%;">
        <i class="sign out alternate red icon"></i>
        Salir
    </a>
</div>
