<div class="ui middle aligned center aligned grid">
        <div class="column">
            <div class="ui left aligned segment" style="background-color: rgba(255,255,255,0.8);">

                <div class="header"><h3>LOGIN</h3></div>

                <div class="ui segments">
                    <div class="ui left aligned segment" style="background-color: rgba(255,255,255,0.8);">
                        <div class="ui left icon input" style="width: 100%;">
                            <input type="text" placeholder="Usuario">
                            <i class="user icon"></i>
                        </div>
                    </div>
                    <div class="ui left aligned segment" style="background-color: rgba(255,255,255,0.8);">
                        <div class="ui left icon input" style="width: 100%;">
                            <input type="password" placeholder="Contraseña">
                            <i class="lock icon"></i>
                        </div>
                    </div>
                    <div class="ui right aligned segment" style="background-color: rgba(255,255,255,0.8);">
                        <a href="http://{{clientbaseurl}}/odontoup/pages/demo/dashboard" class="ui primary button">
                            ACCEDER
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
