<div class="ui middle aligned center aligned grid">
        <div class="column">
            <form id="form1" name="form1" class="ui large form" method="post" v-on:submit.prevent="doLogin">
                <div class="ui left aligned segment" style="background-color: rgba(255,255,255,0.8);">

                    <!-- <div class="header"><h3>LOGIN</h3></div> -->

                    <div class="ui segments">
                        <div class="ui left center segment" style="background-color: rgba(255,255,255,0.8); text-align: center;">
                            <img v-bind:src="basepath + 'web/images/' + appid + '_logo.png'" style="max-width: 150px;" />
                        </div>
                        <div class="ui left aligned segment" style="background-color: rgba(255,255,255,0.8);">
                            <div class="ui left icon input" style="width: 100%;">
                                <input type="text" id="login" name="login" placeholder="Usuario">
                                <i class="user icon"></i>
                            </div>
                        </div>
                        <div class="ui left aligned segment" style="background-color: rgba(255,255,255,0.8);">
                            <div class="ui left icon input" style="width: 100%;">
                                <input type="password" id="password" name="password" placeholder="Contraseña">
                                <i class="lock icon"></i>
                            </div>
                        </div>
                        <div class="ui right aligned segment" style="background-color: rgba(255,255,255,0.8);">
                            <button type="submit" id="loginbutton" class="ui fluid large green button">Acceder</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
