<div class="ui field" v-bind:class="{required: getUiOption('required')}">
    <div class="ui left icon input" style="width: 450px;" v-bind:class="{disabled: getUiOption('readOnly')}">
      <i class="calendar icon"></i>
      <input type="text" ref="realField" v-bind:name="field.id" v-bind:form="forForm">
    </div>
    
    <p v-if="getUiOption('info') != ''" style="font-size:.8em">${ getUiOption('info') }</p>
</div>