<div>
  <div class="ui field" v-bind:class="{required: getUiOption('required')}">
    <div class="ui input" style="width: 450px;" v-bind:class="{disabled: getUiOption('readOnly')}">
      <input type="password" placeholder="" ref="realField" v-bind:name="field.id" v-bind:form="forForm">
    </div>
  </div>
  <div class="ui field" v-bind:class="{required: getUiOption('required')}" style="margin-top:10px;">
    <div class="ui input" style="width: 450px;" v-bind:class="{disabled: getUiOption('readOnly')}">
      <input type="password" placeholder="" ref="realFieldRepeat" >
    </div>
  </div>
  
    <p v-if="getUiOption('info') != ''" style="font-size:.8em">${ getUiOption('info') }</p>
</div>