<div class="ui field" v-bind:class="{required: getUiOption('required')}">
    <div class="ui input" style="width: 450px;" v-bind:class="{disabled: getUiOption('readOnly')}">
      <input v-if="!isTextArea()" type="text" ref="realField" v-bind:name="field.id" v-bind:form="forForm">
      <textarea v-if="isTextArea()" ref="realField" v-bind:name="field.id" v-bind:form="forForm" cols="60" v-bind:rows="getTypeOption('rows')" ></textarea>
    </div>
    <p v-if="getUiOption('info') != ''" style="font-size:.8em">${ getUiOption('info') }</p>
</div>