<div class="ui fluid container main-container">
    <div id="___id_" class="ui padded grid">
        <div class="thirteen wide column">
            <div class="ui segment">
                asd
            </div>
            <div class="ui segment">
                <div class="ui embed" data-url="http://default.localhost/clientes/list"></div>
            </div>
        </div>
        <div class="three wide column" style="padding-left: 0px;">
            dsa
        </div>
    </div>
</div>